### ISSUE TITLE
ClinGen subset as potential inclusion/exclusion criteria

### ISSUE THREAD

**Issue by mellybelly** [everycure-org/matrix-disease-list#3]
I would expect all clingen subset diseases (i.e. those that have undergone lumping and splitting) are included in the list. Is this true? We may wish to include this subset flag in any case because these classes have undergone significant scrutiny as individual disease entities with different mechanisms, phenotypic features, and/or treatments.

**Comment by matentzn** [comment]
THis has been implemented, thanks for the issue, the heuristics does seem to work well!
